apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/order_service"
  DB_USERNAME: root
  INVENTORY_SERVICE_URL: http://inventory-service.default.svc.cluster.local:8082
  INVENTORY_SERVICE_API_VERSION: 1.0.0
  LOKI_URI: loki.default.svc.cluster.local:3100
